import { useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowUpRight, ChevronDown, ChevronRight, Globe2, Mail, MapPin, Menu, Phone, ShieldCheck, Truck, Users, X } from 'lucide-react'

const services = [
  ['01', 'Industrial catering', '28,000+ meals daily, HACCP-certified kitchens, Smart Tray Technology, CCTV kitchen monitoring, and client-specific menus.', 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=900&q=85'],
  ['02', 'Housing solutions', '8,000+ residents housed daily in Aramco-approved camps with clinics, gyms, mini-markets, security, and desalination systems.', 'https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=900&q=85'],
  ['03', 'Facilities management', 'Plumbing, electrical, carpentry, janitorial, security, waste, utilities, pest control, and room attendance.', 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=85'],
  ['04', 'Mobile kitchens', 'Certified mobile kitchens for remote and offshore operations, with setup, support, removal, and rental options.', 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=85'],
  ['05', 'Banqueting & events', 'Custom menus, elegant table setups, live cooking, VIP service crews, and full QHSE compliance.', 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=900&q=85'],
]

const projects = ['URMPP Program - Jafurah & South Ghawar (2022 - Ongoing)', 'Qiddiya Infrastructure Program (2022 - Ongoing)', 'Master Gas Phase II - Aramco (2019-2022)', 'EO/PO Pipelines - Sadara (2019-2022)', 'SABIC - General Construction Projects (2014-2023)']
const locations = ['Jubail', 'Khobar / Dammam', 'Ras Tanoura', 'Turaif', 'Haradth', 'North Jafurah', 'South Jafurah', 'Riyadh', 'Jizan', 'Neom']
const capabilities = ['Engineering & Construction (EPC)', 'Global Supply Chain Management', 'Specialized Cathodic Protection Services', 'Telecom & ICT Infrastructure', 'Asset & Field Solutions', 'Commissioning', 'Project Management', 'Catering & Camp Services']
const clients = ['Saudi Aramco', 'SABIC', 'Maaden', 'Qiddiya', 'NEOM', 'Leading EPC contractors', 'Saudi Fal', 'Halliburton', 'Al Muhaidib Contracting', 'CAT Group', 'Larsen & Toubro', 'Bilfal Heavy Industries']

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const scrollTo = (id) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false) }
  return <main><style>{`.sisco-logo{display:inline-flex;flex-direction:column;line-height:.8;color:currentColor;min-width:48px}.sisco-logo i{font-size:11px;font-style:normal;font-weight:700}.sisco-logo b{font-size:15px;letter-spacing:-.08em}.client-logo-grid{margin-top:10px}.client-logo{min-height:105px;display:flex;flex-direction:column;justify-content:center;gap:8px}.client-logo span{color:var(--orange);font:10px 'DM Mono',monospace}.client-logo h3{font-size:16px;margin:0}.client-logo small{color:var(--muted);font:8px 'DM Mono',monospace;letter-spacing:.12em}`}</style>
    <nav className="nav-shell" aria-label="Main navigation"><button className="brand" onClick={() => scrollTo('top')} aria-label="SISCO Catering home"><span className="sisco-logo"><i>سيسكو</i><b>SISCO</b></span><span><strong>SISCO</strong><small>CATERING & FM</small></span></button><div className={`nav-links ${menuOpen ? 'is-open' : ''}`}><button onClick={() => scrollTo('about')}>About</button><button onClick={() => scrollTo('services')}>Services</button><button onClick={() => scrollTo('projects')}>Projects</button><button onClick={() => scrollTo('standards')}>QHSE</button><button onClick={() => scrollTo('contact')}>Contact</button></div><button className="nav-cta" onClick={() => scrollTo('contact')}>Talk to our team <ArrowUpRight size={16} /></button><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></nav>

    <section className="hero" id="top"><div className="hero-image" /><div className="hero-overlay" /><div className="hero-content page-pad"><motion.p className="eyebrow light" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }}>Specialized Industrial Services Co. Ltd</motion.p><motion.h1 initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }}>Integrated services<br /><em>for the Kingdom's</em><br />critical operations.</motion.h1><div className="hero-bottom"><p>Engineering, procurement, construction, catering, accommodation, supply chain, and operational support across Saudi Arabia.</p><button className="circle-button" onClick={() => scrollTo('about')} aria-label="Explore SISCO"><ChevronDown size={20} /></button></div></div><div className="hero-meta"><span>EST. 1990</span><span className="hero-line" /><span>100% SAUDI-OWNED</span></div></section>

    <section className="intro section-pad" id="about"><div className="intro-stamp"><ShieldCheck size={18} /><span>Safety first<br />always</span></div><div className="intro-copy"><p className="eyebrow">About SISCO</p><h2>Trusted partner for<br /><em>Vision 2030 transformation.</em></h2><p className="lead">SISCO delivers engineering, procurement, construction, commissioning, global supply chain solutions, and asset and field solutions to key growth sectors in the Kingdom of Saudi Arabia.</p><p className="body-copy">We serve oil & gas, buildings & infrastructure, petrochemical, mining, and metals sectors with comprehensive EPC, maintenance, industrial, and operational support services.</p></div><div className="intro-stats"><div><strong>1990</strong><span>year<br />established</span></div><div><strong>5,500<span>+</span></strong><span>employees<br />across KSA</span></div><div><strong>107m<span>+</span></strong><span>safe<br />manhours</span></div><div><strong>2b<span>+</span></strong><span>SAR annual<br />procurement</span></div></div></section>

    <section className="statement section-pad"><div className="statement-image" /><div className="statement-content"><p className="eyebrow light">Who we are</p><h2>Operational excellence<br /><em>with a Saudi heart.</em></h2><p>Privately owned and 100% Saudi, SISCO has served the Kingdom for more than 35 years. Our teams mobilize people, resources, equipment, and governance wherever clients need dependable execution.</p><div className="signature">People. Safety. Performance.</div></div></section>

    <section className="services section-pad" id="services"><div className="section-heading"><div><p className="eyebrow">Our capabilities</p><h2>From site to<br /><em>service.</em></h2></div><p className="heading-note">One operating partner for<br />complex industrial environments.</p></div><div className="service-grid">{services.map(([number, title, copy, image], index) => <motion.article className="service-card" key={title} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .06 }}><div className="service-image"><img src={image} alt="" /><span>{number}</span></div><div className="service-info"><h3>{title}</h3><p>{copy}</p></div></motion.article>)}</div></section>

    <section className="standards section-pad" id="standards"><div className="section-heading"><div><p className="eyebrow">QHSE & differentiation</p><h2>Built for precision.<br /><em>Powered by safety.</em></h2></div></div><div className="standards-grid"><div><ShieldCheck size={25} /><h3>Safety culture</h3><p>Executive HSE leadership, training centers, safety-first culture, proactive risk management, and continuous improvement.</p></div><div><Truck size={25} /><h3>Fast mobilization</h3><p>Proven execution excellence, flexible LSTK and reimbursable commercial models, and robust project management systems.</p></div><div><Users size={25} /><h3>Certified training</h3><p>First Aid, H2S Awareness, Fire Safety, HACCP, Highfield preparation, and continuing employee HSE training.</p></div><div><Globe2 size={25} /><h3>Certified systems</h3><p>ISO 9001 Quality, ISO 22000 Food Safety, ISO 14001 Environmental, ISO 45001 Health and Safety, and HACCP compliance.</p></div></div></section>

    <section className="section-pad" id="catering-detail"><div className="section-heading"><div><p className="eyebrow">Integrated industrial catering solutions</p><h2>Quality you can<br /><em>trace.</em></h2></div><p className="heading-note">Built for precision.<br />Powered by safety.</p></div><div className="why-grid"><div><strong>01</strong><h3>Culinary excellence</h3><p>High-quality, culturally inclusive meals prepared by experienced international chefs.</p></div><div><strong>02</strong><h3>Food safety & compliance</h3><p>HACCP-certified operations aligned with Aramco standards for hygiene and regulatory adherence.</p></div><div><strong>03</strong><h3>Advanced packaging</h3><p>Contaminant-free packaging with thermal control, X-ray scanning, and real-time verification.</p></div><div><strong>04</strong><h3>Kitchen technology</h3><p>Digitized kitchen systems for efficient production, quality control, and consistent output.</p></div><div><strong>05</strong><h3>Traceability</h3><p>Full tracking of food production and delivery from source to service, with sample retention protocols.</p></div><div><strong>06</strong><h3>Temperature-controlled logistics</h3><p>GPS-monitored fleet with insulated compartments for safe, timely delivery of hot and cold meals.</p></div><div><strong>07</strong><h3>Client customization</h3><p>Flexible menus and dietary plans tailored from large-scale industrial to VIP catering.</p></div></div></section>

    <section className="network section-pad" id="network"><div className="network-copy"><p className="eyebrow">Our strategic project network</p><h2>Ready wherever<br /><em>the work is.</em></h2><p>Nationwide project execution centers mobilize teams and resources across the Kingdom.</p><div className="location-list">{locations.map((location, index) => <div key={location}><span>0{index + 1}</span>{location}<ChevronRight size={15} /></div>)}</div></div><div className="network-map"><div className="standards-grid"><div><strong>24/7</strong><h3>Operational support</h3><p>Continuous catering, housing, facilities, and logistics coverage.</p></div><div><strong>17+</strong><h3>Supply countries</h3><p>Digital procurement and a robust international supplier network.</p></div><div><strong>3,500</strong><h3>Residents supported</h3><p>Scalable South Jafurah life-support capacity.</p></div><div><strong>100%</strong><h3>Kingdom focus</h3><p>Regional teams ready for onshore, offshore, and remote projects.</p></div></div><p>Our operational network spans Jubail, Khobar / Dammam, Ras Tanoura, Turaif, Haradth, North & South Jafurah, Riyadh, Jizan, and Neom.</p></div></section>

    <section className="section-pad" id="projects"><div className="section-heading"><div><p className="eyebrow">Key projects</p><h2>Delivery at<br /><em>Kingdom scale.</em></h2></div></div><div className="news-grid">{projects.map(project => <article key={project}><div className="news-date">PROJECT<span>REFERENCE</span></div><h3>{project}</h3><ArrowUpRight size={18} /></article>)}</div></section>

    <section className="why section-pad" id="roadmap"><div><p className="eyebrow">Vision 2030 roadmap</p><h2>Growth.<br /><em>Innovation.</em><br />Sustainability.</h2></div><div className="why-grid"><div><strong>EXPANSION</strong><h3>Scale housing capacity</h3><p>Increase resident capacity by 2026.</p></div><div><strong>INNOVATION</strong><h3>Boost meal production</h3><p>Increase daily production to 40,000+ meals by 2030 with AI-driven kitchens.</p></div><div><strong>SUSTAINABILITY</strong><h3>Net-zero emission</h3><p>Transition all camps to solar / hybrid energy by 2030.</p></div><div><strong>TECHNOLOGY</strong><h3>AI integration</h3><p>Reduce food waste by 20% via predictive analytics between 2026 and 2028.</p></div><div><strong>WASTE TO RESOURCE</strong><h3>Composting growth</h3><p>Expand composting from 5 to 15 tons per month by 2027 for urban farming partnerships.</p></div><div><strong>SMART HOUSING</strong><h3>Resident app</h3><p>Launch an IoT-enabled resident app in 2027 for utilities and community engagement.</p></div></div></section>

    <section className="section-pad" id="csr"><div className="section-heading"><div><p className="eyebrow">Corporate social responsibility</p><h2>Impact beyond<br /><em>operations.</em></h2></div></div><div className="standards-grid"><div><Users size={25} /><h3>Community engagement</h3><p>Sponsorship of local sports events, charity organizations, and public health initiatives.</p></div><div><MapPin size={25} /><h3>Local hiring</h3><p>Supporting local workforce and economic growth across the regions where we operate.</p></div><div><Globe2 size={25} /><h3>Social initiatives</h3><p>Partnering with municipalities for waste sorting and environmental awareness programs.</p></div><div><ShieldCheck size={25} /><h3>Safety & environment</h3><p>Public food safety awareness, in-house fresh produce, zero food waste policy, and community clean-up initiatives.</p></div></div></section>

    <section className="section-pad" id="clients"><div className="section-heading"><div><p className="eyebrow">Our clients & partners</p><h2>Trusted by<br /><em>industry leaders.</em></h2></div></div><div className="standards-grid client-logo-grid">{clients.map((client, index) => <div className="client-logo" key={client}><span>0{index + 1}</span><h3>{client}</h3><small>CLIENT & PARTNER</small></div>)}</div></section>

    <section className="contact" id="contact"><div className="contact-inner"><p className="eyebrow light">Contact SISCO</p><h2>Let’s support<br /><em>your operation.</em></h2><p>SISCO Head Office, 9665 King Faisal Ibn Abdulaziz, Al Bahar, Al Khobar 34218, Saudi Arabia.</p><div className="contact-details"><a href="tel:+966138297800"><Phone size={17} />+966 (13) 829 7800 - Ext. 7971</a><a href="mailto:Info.catering@siscosaudi.com"><Mail size={17} />Info.catering@siscosaudi.com</a><a href="mailto:info@siscosaudi.com"><Mail size={17} />info@siscosaudi.com</a><span><MapPin size={17} />Khobar, Saudi Arabia</span></div></div><div className="contact-side">EPC <span>•</span> Supply Chain <span>•</span> Catering <span>•</span> FM</div></section>

    <footer><div className="footer-brand"><span className="sisco-logo"><i>سيسكو</i><b>SISCO</b></span><span><strong>SISCO</strong><small>CATERING & FM</small></span></div><p>Engineering, industrial, catering,<br />and operational support services.</p><div className="footer-links"><button onClick={() => scrollTo('services')}>Services</button><button onClick={() => scrollTo('projects')}>Projects</button><button onClick={() => scrollTo('clients')}>Partners</button><a href="https://siscosaudi.com/" target="_blank" rel="noreferrer" aria-label="SISCO website"><ArrowUpRight size={17} /></a></div><small className="copyright">© 2026 Specialized Industrial Services Co. Ltd.</small></footer>
  </main>
}

export default App
